services:
  # 后端API服务
  - type: web
    name: yiqi-hotel-api
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: ALLOWED_ORIGINS
        value: "https://yiqi-hotel.vercel.app"
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: yiqi-hotel-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: yiqi-hotel-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: yiqi-hotel-db
          property: password

# 数据库服务
databases:
  - name: yiqi-hotel-db
    plan: free
    region: singapore
    ipAllowList: []
