services:
  # 后端API服务
  - type: web
    name: hotel-api-devbox
    env: java
    plan: free
    region: singapore # 选择离你最近的区域，可以是 singapore, frankfurt, oregon 等
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: hotel-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: hotel-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: hotel-db
          property: password
      - key: ALLOWED_ORIGINS
        value: "https://yiqi-hotel.vercel.app" # 更新为你的实际前端域名

# 数据库服务
databases:
  - name: hotel-db
    plan: free
    region: singapore # 选择与Web服务相同的区域
    ipAllowList: [] # 允许所有IP访问
